Added apoc-core
neo4j/docker-neo4j pull request #302
Opened 2021-07-09 14:25 UTC by renetapopova

2021-07-09 14:29 UTC, eastlondoner requested changes

2021-07-09 14:29 UTC, eastlondoner commented on docker-image-src/4.4/docker-entrypoint.sh
> +        install_plugin_from_location "${_location}"
@renetapopova you'll need to implement install_plugin_from_location ;-)

2021-07-12 05:26 UTC, eastlondoner commented
Nice try.

Install_plugin_from_location
needs to take a local location (/var/lib/neo4j/labs/*) and copy it to the plugins directory using cp

2021-07-12 05:30 UTC, eastlondoner requested changes

2021-07-12 05:30 UTC, eastlondoner commented on neo4jlabs-plugins.json
> +    "location": "/labs/apoc-core-*.jar",
I think this should be a full path so /var/lib/neo4j/labs...

2021-07-12 05:30 UTC, eastlondoner commented on docker-image-src/4.4/docker-entrypoint.sh
> +  local _plugin_name="${1}" #e.g. apoc-core
The passed argument will be the location not plug-in name

2021-07-13 11:05 UTC, renetapopova commented
@eastlondoner I decided to keep the `plugin_name`as a parameter so that the function follows the same pattern as the rest; I can validate that the destination is readable, and the message is the same. I haven't tested it, I am also not sure what will happen if there are more apoc-core jar files in the location (in my Neo4j's` /labs` folder there are no jars), I guess the function will copy them all one by one.

2021-07-13 12:09 UTC, eastlondoner reviewed
@renetapopova this looks great - leave the PR up and I will add a test

2021-07-20 07:43 UTC, jennyowen approved these changes

2021-07-20 07:49 UTC, eastlondoner approved these changes
LGTM please Squash and merge :-)

2021-07-20 08:02 UTC, merged