Fix mac plugin permissions
neo4j/docker-neo4j pull request #459
Opened 2023-08-31 09:27 UTC by stefgia

* Set correct permissions for plugins in mounted folder in mac
* Fix bash syntax for mac
* Minor documentation fix

2023-08-31 10:20 UTC, jennyowen requested changes
this looks mostly fine, there's just a few changes. 
IMHO this test doesn't belong with the mounting tests, but it definitely needs a name that actually describes what it's testing.

2023-08-31 10:20 UTC, jennyowen commented on src/test/java/com/neo4j/docker/coredb/TestMounting.java
> +	void shouldLoadPluginsFromMountedFolder() throws Exception {
The test name does not describe what's happening in the test.
It's testing that the bundled apoc plugin can be moved into the `/plugins` folder when something is mounted to `/plugins`. 

It's more of a test of the plugins downloading/moving infrastructure than anything to do with mounting. 

I think it should be in `TestPluginInstallation.java` instead.

2023-08-31 10:20 UTC, jennyowen commented on src/test/java/com/neo4j/docker/coredb/TestMounting.java
> +			assertApocIsLoaded(container);
We should also be testing that the plugins folder created in line 356 actually contains apoc.jar.

2023-09-01 09:07 UTC, jennyowen requested changes
only small changes this time :)

2023-09-01 09:38 UTC, stefgia commented on src/test/java/com/neo4j/docker/coredb/plugins/TestPluginInstallation.java
> +            var pluginsFolder = Arrays.stream( Objects.requireNonNull( testOutputFolder.toFile().listFiles() ) ).findFirst();
Because I had no idea it does :D

2023-09-01 09:41 UTC, stefgia commented on src/test/java/com/neo4j/docker/coredb/plugins/TestPluginInstallation.java
> +            Assertions.assertTrue( Arrays.stream( Objects.requireNonNull( pluginsFolder.get().toPath().toFile().listFiles() ) ).findFirst().get().getName().equalsIgnoreCase( "bloom.jar" ));
indeed that looks better

2023-09-01 09:58 UTC, jennyowen approved these changes
Great!

2023-09-01 13:15 UTC, merged